name: Portfolio Deployment
on:
    push:
        branches:
            - master
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Master
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm install
            - name: Build
              env:
                CI: false
              run: npm run build
            - name: Upload Bild Files
              uses: actions/upload-artifact@v4
              with:
                name: build
                path: build
    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout master
              uses: actions/checkout@v4
            - name : Download build files
              uses: actions/download-artifact@v4
              with:
                name: build
                path: build
            - name: Install Firebase CLI
              run: npm install -g firebase-tools
            - name: Deploy to firebase
              env:
                  FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
              run: |
                  firebase use --add react-portfolio-a037c
                  firebase deploy --only hosting
            
            
